DROP TABLE IF EXISTS games;

CREATE TABLE games (
    game_pk             INTEGER NOT NULL UNIQUE,
    game_guid           TEXT,
    game_type           TEXT    NOT NULL,
    season              TEXT    NOT NULL,
    game_date           TEXT    NOT NULL,
    official_date       TEXT    NOT NULL,
    status_abstract     TEXT    NOT NULL,
    status_detailed     TEXT    NOT NULL,
    status_code         TEXT    NOT NULL,
    start_time_tbd      INTEGER NOT NULL DEFAULT 0,
    away_team_id        INTEGER NOT NULL,
    away_team_name      TEXT    NOT NULL,
    away_score          INTEGER,
    away_is_winner      INTEGER,
    home_team_id        INTEGER NOT NULL,
    home_team_name      TEXT    NOT NULL,
    home_score          INTEGER,
    home_is_winner      INTEGER,
    venue_id            INTEGER NOT NULL,
    venue_name          TEXT    NOT NULL,
    day_night           TEXT,
    description         TEXT,
    series_description  TEXT,
    series_game_number  INTEGER,
    games_in_series     INTEGER,
    double_header       TEXT    NOT NULL DEFAULT 'N',
    game_number         INTEGER NOT NULL DEFAULT 1,
    scheduled_innings   INTEGER NOT NULL DEFAULT 9,
    is_tie              INTEGER NOT NULL DEFAULT 0,
    created_at          TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);
